/*!
 * jQuery Transit - CSS3 transitions and transformations
 * (c) 2011-2012 Rico Sta. Cruz
 * MIT Licensed.
 *
 * http://ricostacruz.com/jquery.transit
 * http://github.com/rstacruz/jquery.transit
 */

(function(d){function n(a){if(a in l.style)return a;var b=["Moz","Webkit","O","ms"],c=a.charAt(0).toUpperCase()+a.substr(1);if(a in l.style)return a;for(a=0;a<b.length;++a){var d=b[a]+c;if(d in l.style)return d}}function m(a){"string"===typeof a&&this.parse(a);return this}function t(a,b,c){!0===b?a.queue(c):b?a.queue(b,c):c()}function v(a){var b=[];d.each(a,function(a){a=d.camelCase(a);a=d.transit.propertyMap[a]||d.cssProps[a]||a;a=q(a);e[a]&&(a=q(e[a]));-1===d.inArray(a,b)&&b.push(a)});return b}
function u(a,b,c,e){a=v(a);d.cssEase[c]&&(c=d.cssEase[c]);var h=""+r(b)+" "+c;0<parseInt(e,10)&&(h+=" "+r(e));var f=[];d.each(a,function(a,b){f.push(b+" "+h)});return f.join(", ")}function f(a,b){b||(d.cssNumber[a]=!0);d.transit.propertyMap[a]=e.transform;d.cssHooks[a]={get:function(b){return d(b).css("transit:transform").get(a)},set:function(b,e){var h=d(b).css("transit:transform");h.setFromString(a,e);d(b).css({"transit:transform":h})}}}function q(a){return a.replace(/([A-Z])/g,function(a){return"-"+
a.toLowerCase()})}function k(a,b){return"string"!==typeof a||a.match(/^[\-0-9\.]+$/)?""+a+b:a}function r(a){"string"!==typeof a||a.match(/^[\-0-9\.]+/)||(a=d.fx.speeds[a]||d.fx.speeds._default);return k(a,"ms")}d.transit={version:"0.9.9",propertyMap:{marginLeft:"margin",marginRight:"margin",marginBottom:"margin",marginTop:"margin",paddingLeft:"padding",paddingRight:"padding",paddingBottom:"padding",paddingTop:"padding"},enabled:!0,useTransitionEnd:!1};var l=document.createElement("div"),e={},w=-1<
navigator.userAgent.toLowerCase().indexOf("chrome");e.transition=n("transition");e.transitionDelay=n("transitionDelay");e.transform=n("transform");e.transformOrigin=n("transformOrigin");e.filter=n("Filter");l.style[e.transform]="";l.style[e.transform]="rotateY(90deg)";e.transform3d=""!==l.style[e.transform];var s=e.transitionEnd={transition:"transitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",WebkitTransition:"webkitTransitionEnd",msTransition:"MSTransitionEnd"}[e.transition]||
null,p;for(p in e)e.hasOwnProperty(p)&&"undefined"===typeof d.support[p]&&(d.support[p]=e[p]);l=null;d.cssEase={_default:"ease","in":"ease-in",out:"ease-out","in-out":"ease-in-out",snap:"cubic-bezier(0,1,.5,1)",easeOutCubic:"cubic-bezier(.215,.61,.355,1)",easeInOutCubic:"cubic-bezier(.645,.045,.355,1)",easeInCirc:"cubic-bezier(.6,.04,.98,.335)",easeOutCirc:"cubic-bezier(.075,.82,.165,1)",easeInOutCirc:"cubic-bezier(.785,.135,.15,.86)",easeInExpo:"cubic-bezier(.95,.05,.795,.035)",easeOutExpo:"cubic-bezier(.19,1,.22,1)",
easeInOutExpo:"cubic-bezier(1,0,0,1)",easeInQuad:"cubic-bezier(.55,.085,.68,.53)",easeOutQuad:"cubic-bezier(.25,.46,.45,.94)",easeInOutQuad:"cubic-bezier(.455,.03,.515,.955)",easeInQuart:"cubic-bezier(.895,.03,.685,.22)",easeOutQuart:"cubic-bezier(.165,.84,.44,1)",easeInOutQuart:"cubic-bezier(.77,0,.175,1)",easeInQuint:"cubic-bezier(.755,.05,.855,.06)",easeOutQuint:"cubic-bezier(.23,1,.32,1)",easeInOutQuint:"cubic-bezier(.86,0,.07,1)",easeInSine:"cubic-bezier(.47,0,.745,.715)",easeOutSine:"cubic-bezier(.39,.575,.565,1)",
easeInOutSine:"cubic-bezier(.445,.05,.55,.95)",easeInBack:"cubic-bezier(.6,-.28,.735,.045)",easeOutBack:"cubic-bezier(.175, .885,.32,1.275)",easeInOutBack:"cubic-bezier(.68,-.55,.265,1.55)"};d.cssHooks["transit:transform"]={get:function(a){return d(a).data("transform")||new m},set:function(a,b){var c=b;c instanceof m||(c=new m(c));a.style[e.transform]="WebkitTransform"!==e.transform||w?c.toString():c.toString(!0);d(a).data("transform",c)}};d.cssHooks.transform={set:d.cssHooks["transit:transform"].set};
d.cssHooks.filter={get:function(a){return a.style[e.filter]},set:function(a,b){a.style[e.filter]=b}};"1.8">d.fn.jquery&&(d.cssHooks.transformOrigin={get:function(a){return a.style[e.transformOrigin]},set:function(a,b){a.style[e.transformOrigin]=b}},d.cssHooks.transition={get:function(a){return a.style[e.transition]},set:function(a,b){a.style[e.transition]=b}});f("scale");f("translate");f("rotate");f("rotateX");f("rotateY");f("rotate3d");f("perspective");f("skewX");f("skewY");f("x",!0);f("y",!0);m.prototype=
{setFromString:function(a,b){var c="string"===typeof b?b.split(","):b.constructor===Array?b:[b];c.unshift(a);m.prototype.set.apply(this,c)},set:function(a){var b=Array.prototype.slice.apply(arguments,[1]);this.setter[a]?this.setter[a].apply(this,b):this[a]=b.join(",")},get:function(a){return this.getter[a]?this.getter[a].apply(this):this[a]||0},setter:{rotate:function(a){this.rotate=k(a,"deg")},rotateX:function(a){this.rotateX=k(a,"deg")},rotateY:function(a){this.rotateY=k(a,"deg")},scale:function(a,
b){void 0===b&&(b=a);this.scale=a+","+b},skewX:function(a){this.skewX=k(a,"deg")},skewY:function(a){this.skewY=k(a,"deg")},perspective:function(a){this.perspective=k(a,"px")},x:function(a){this.set("translate",a,null)},y:function(a){this.set("translate",null,a)},translate:function(a,b){void 0===this._translateX&&(this._translateX=0);void 0===this._translateY&&(this._translateY=0);null!==a&&void 0!==a&&(this._translateX=k(a,"px"));null!==b&&void 0!==b&&(this._translateY=k(b,"px"));this.translate=this._translateX+
","+this._translateY}},getter:{x:function(){return this._translateX||0},y:function(){return this._translateY||0},scale:function(){var a=(this.scale||"1,1").split(",");a[0]&&(a[0]=parseFloat(a[0]));a[1]&&(a[1]=parseFloat(a[1]));return a[0]===a[1]?a[0]:a},rotate3d:function(){for(var a=(this.rotate3d||"0,0,0,0deg").split(","),b=0;3>=b;++b)a[b]&&(a[b]=parseFloat(a[b]));a[3]&&(a[3]=k(a[3],"deg"));return a}},parse:function(a){var b=this;a.replace(/([a-zA-Z0-9]+)\((.*?)\)/g,function(a,d,e){b.setFromString(d,
e)})},toString:function(a){var b=[],c;for(c in this)this.hasOwnProperty(c)&&(e.transform3d||"rotateX"!==c&&"rotateY"!==c&&"perspective"!==c&&"transformOrigin"!==c)&&"_"!==c[0]&&(a&&"scale"===c?b.push(c+"3d("+this[c]+",1)"):a&&"translate"===c?b.push(c+"3d("+this[c]+",0)"):b.push(c+"("+this[c]+")"));return b.join(" ")}};d.fn.transition=d.fn.transit=function(a,b,c,f){var h=this,k=0,l=!0,g=jQuery.extend(!0,{},a);"function"===typeof b&&(f=b,b=void 0);"object"===typeof b&&(c=b.easing,k=b.delay||0,l=b.queue||
!0,f=b.complete,b=b.duration);"function"===typeof c&&(f=c,c=void 0);"undefined"!==typeof g.easing&&(c=g.easing,delete g.easing);"undefined"!==typeof g.duration&&(b=g.duration,delete g.duration);"undefined"!==typeof g.complete&&(f=g.complete,delete g.complete);"undefined"!==typeof g.queue&&(l=g.queue,delete g.queue);"undefined"!==typeof g.delay&&(k=g.delay,delete g.delay);"undefined"===typeof b&&(b=d.fx.speeds._default);"undefined"===typeof c&&(c=d.cssEase._default);b=r(b);var n=u(g,b,c,k),m=d.transit.enabled&&
e.transition?parseInt(b,10)+parseInt(k,10):0;if(0===m)return t(h,l,function(a){h.css(g);f&&f.apply(h);a&&a()}),h;var p={},q=function(b){var c=!1,g=function(){c&&h.unbind(s,g);0<m&&h.each(function(){this.style[e.transition]=p[this]||null});"function"===typeof f&&f.apply(h);"function"===typeof b&&b()};0<m&&s&&d.transit.useTransitionEnd?(c=!0,h.bind(s,g)):window.setTimeout(g,m);h.each(function(){0<m&&(this.style[e.transition]=n);d(this).css(a)})};t(h,l,function(a){this.offsetWidth;q(a)});return this};
d.transit.getTransitionValue=u})(jQuery);